// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace PlesniKlubovi.Migrations
{
    [DbContext(typeof(PlesniKluboviContext))]
    [Migration("20220321100659_V5")]
    partial class V5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.ClanKluba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DatumRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("JB")
                        .HasColumnType("int");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PlesniKlubID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex("PlesniKlubID");

                    b.ToTable("Clan Kluba");
                });

            modelBuilder.Entity("Models.Clanarina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("Mesec")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Clanarina");
                });

            modelBuilder.Entity("Models.Placanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int?>("ClanKlubaID")
                        .HasColumnType("int");

                    b.Property<int?>("ClanarinaID")
                        .HasColumnType("int");

                    b.Property<int?>("PlesID")
                        .HasColumnType("int");

                    b.Property<int?>("PlesniKlubID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClanKlubaID");

                    b.HasIndex("ClanarinaID");

                    b.HasIndex("PlesID");

                    b.HasIndex("PlesniKlubID");

                    b.ToTable("ClanoviPlesovi");
                });

            modelBuilder.Entity("Models.Ples", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Ples");
                });

            modelBuilder.Entity("Models.PlesniKlub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<int?>("PlesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlesID");

                    b.ToTable("Plesni Klub");
                });

            modelBuilder.Entity("Models.ClanKluba", b =>
                {
                    b.HasOne("Models.PlesniKlub", "PlesniKlub")
                        .WithMany("ClanoviKluba")
                        .HasForeignKey("PlesniKlubID");

                    b.Navigation("PlesniKlub");
                });

            modelBuilder.Entity("Models.Placanje", b =>
                {
                    b.HasOne("Models.ClanKluba", "ClanKluba")
                        .WithMany("ClanPles")
                        .HasForeignKey("ClanKlubaID");

                    b.HasOne("Models.Clanarina", "Clanarina")
                        .WithMany("ClanoviPlesovi")
                        .HasForeignKey("ClanarinaID");

                    b.HasOne("Models.Ples", "Ples")
                        .WithMany("PlesClan")
                        .HasForeignKey("PlesID");

                    b.HasOne("Models.PlesniKlub", "PlesniKlub")
                        .WithMany("Placanja")
                        .HasForeignKey("PlesniKlubID");

                    b.Navigation("Clanarina");

                    b.Navigation("ClanKluba");

                    b.Navigation("Ples");

                    b.Navigation("PlesniKlub");
                });

            modelBuilder.Entity("Models.PlesniKlub", b =>
                {
                    b.HasOne("Models.Ples", null)
                        .WithMany("PlesniKlub")
                        .HasForeignKey("PlesID");
                });

            modelBuilder.Entity("Models.ClanKluba", b =>
                {
                    b.Navigation("ClanPles");
                });

            modelBuilder.Entity("Models.Clanarina", b =>
                {
                    b.Navigation("ClanoviPlesovi");
                });

            modelBuilder.Entity("Models.Ples", b =>
                {
                    b.Navigation("PlesClan");

                    b.Navigation("PlesniKlub");
                });

            modelBuilder.Entity("Models.PlesniKlub", b =>
                {
                    b.Navigation("ClanoviKluba");

                    b.Navigation("Placanja");
                });
#pragma warning restore 612, 618
        }
    }
}
